// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



await Firebase.initializeApp(
  options = DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhHWgEmjZpsoWPRswYVa--nu3UnIgllo',
    appId: '1:862805948816:web:79a0b25df5f1f128b99b15',
    messagingSenderId: '862805948816',
    projectId: 'study-io-ad963',
    authDomain: 'study-io-ad963.firebaseapp.com',
    storageBucket: 'study-io-ad963.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtQlFis6QacG0yN0JlS0mF_HpIOU0OZ8',
    appId: '1:862805948816:android:76a630ca77694f34b99b15',
    messagingSenderId: '862805948816',
    projectId: 'study-io-ad963',
    storageBucket: 'study-io-ad963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnK6jnnhx4acdk0t741rG7H7Ge0i_JSfg',
    appId: '1:862805948816:ios:d4ca36f203a48a8fb99b15',
    messagingSenderId: '862805948816',
    projectId: 'study-io-ad963',
    storageBucket: 'study-io-ad963.firebasestorage.app',
    iosClientId: '862805948816-p659hgdppgspb5nn103i7n591rk5am6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnK6jnnhx4acdk0t741rG7H7Ge0i_JSfg',
    appId: '1:862805948816:ios:d4ca36f203a48a8fb99b15',
    messagingSenderId: '862805948816',
    projectId: 'study-io-ad963',
    storageBucket: 'study-io-ad963.firebasestorage.app',
    iosClientId: '862805948816-p659hgdppgspb5nn103i7n591rk5am6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyIo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhhHWgEmjZpsoWPRswYVa--nu3UnIgllo',
    appId: '1:862805948816:web:b589032abfb5e836b99b15',
    messagingSenderId: '862805948816',
    projectId: 'study-io-ad963',
    authDomain: 'study-io-ad963.firebaseapp.com',
    storageBucket: 'study-io-ad963.firebasestorage.app',
  );
}
